languaje: node_js
cache:
  directories
    - node_modules
    - ~/.npm
node_js:
 - '14'

git:
  depth: 3

script:
  - yarn build

notifications:
  email:
    recipients:
      - cruz_har@hotmail.es
      - idas.desing@gmail.com
    on_success: always
    on_failure: always

deploy:
  provider: pages
  skip-cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy del proyecto by Idas"
  on:
    branch: master
    
